services:
  - type: web
    name: newsletter-service-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://newsletter-service-backend.onrender.com
