services:
  - type: web
    name: newsletter-service-backend
    env: docker
    buildCommand: docker build -t newsletter-service-backend .
    startCommand: docker run -p $PORT:8000 -v $(pwd)/data:/app/data newsletter-service-backend
    envVars:
      - key: PORT
        value: 8000
      - key: NODE_ENV
        value: production
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
    plan: starter
    healthCheckPath: /api/health
    autoDeploy: true
