services:
  - type: web
    name: newsletter-service-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 8000
      - key: NODE_ENV
        value: production
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    buildFilter:
      paths:
        - backend/**
    plan: starter
    healthCheckPath: /api/health
    autoDeploy: true
    dockerCommand: node src/index.js
    dockerfilePath: Dockerfile
